spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gym_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: developer
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 60000
      validation-timeout: 5000
      initialization-fail-timeout: 0
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update  # Cambiar de validate a update temporalmente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # Configuraciones adicionales para evitar problemas
        connection.provider_disables_autocommit: true
        order_updates: true
        order_inserts: true
        jdbc.batch_size: 20
    open-in-view: false  # Importante para evitar problemas

  # Deshabilitar inicialización de datos si no es necesaria
  sql:
    init:
      mode: never

# Configuración específica para JPA
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.gym: DEBUG