spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: developer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.gym.controller: DEBUG
    com.gym.service: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081